apiVersion: apps/v1
kind: Deployment
metadata:
  name: clock-app-server
spec:
  selector:
    matchLabels:
      app: clock-app-server
  replicas: 1
  template:
    metadata:
      labels:
        app: clock-app-server
    spec:
      containers:
        - name: clock-app-server
          image: wrujel/clock-app-server
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: env-variables
                  key: PORT
            - name: TIME_API_URL
              valueFrom:
                secretKeyRef:
                  name: env-variables
                  key: TIME_API_URL
            - name: GEO_API_URL
              valueFrom:
                secretKeyRef:
                  name: env-variables
                  key: GEO_API_URL
            - name: GEO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: env-variables
                  key: GEO_API_KEY
            - name: QUOTE_API_URL
              valueFrom:
                secretKeyRef:
                  name: env-variables
                  key: QUOTE_API_URL
