apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clock-app-server-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: clock-app-server
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: 'gce'
spec:
  defaultBackend:
    service:
      name: clock-app-server-service
      port:
        number: 80
